export const SET_ALIVE_EPISODES = 'SET_ALIVE_EPISODES';
export const SET_DEAD_EPISODES = 'SET_DEAD_EPISODES';
export const SET_SHARED_EPISODES = 'SET_SHARED_EPISODES';
export const CLEAR_SHARED_EPISODES = 'CLEAR_SHARED_EPISODES'